### ISSUE TITLE
[Feature] Live Object Proxy

### ISSUE THREAD

**Issue by nbrugger-tgm** [nbrugger-tgm/reactj#35]
At the current state proxies are only createable using the `ReactiveProxy.create` (and `createProxy`) method.

This creates a few inconveniences and also non-useability of 3rd party classes. If for example you use a framework which delivers you constructed objects you can't make them reactable.

**Goal :** make it possible to create proxies from already existing objects.
**No Goal :** replace the old way, just add the new one.
### Before
```java
Preferences pref = ReactiveProxy.create(Preferences.class, 0.3f);
```
### After
```java
Preferences pref = new Preferences(0.3f);
pref = ReactiveProxy.wrap(pref);
```

### Task List

- [x] implement feature
- [x] unify old logic to use wrap
- [x] add test cases
- [x] add documentation(wiki) entry

**Comment by nbrugger-tgm** [comment]
### Done
The feature is available as of commit `ca04221` and will be release in `3.1.0b3`
